### PR TITLE
Fix grammar mistakes in installation

### PR DESCRIPTION
**Pull request by parakeet-live**

### CODE REVIEW

**Review by parakeet-live — COMMENTED** [review]
Wait, hold up, let me fix a grammar error i missed

**Comment by parakeet-live** [comment]
Done!

**Comment by Rix565** [comment]
Don't like exactly the new file.
You don't change grammar mistakes, you change the **whole thing, and I'm not very fan**...

**Comment by parakeet-live** [comment]
I only thought it would be better, but I understand. I'll create a new pull request with actual fixes.

**Pull request closed without merging**
